# Generated by Django 3.1.7 on 2021-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='Badge',
            field=models.CharField(choices=[('B1', 'Bronze1'), ('B2', 'Bronze2'), ('B3', 'Bronze1'), ('S1', 'Silver1'), ('S2', 'Silver2'), ('S3', 'Silve3')], default='Bronze1', max_length=128),
        ),
    ]
